package com.taxzone.app.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF0F172A)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFE2E8F0)
val md_theme_light_onPrimaryContainer = Color(0xFF0F172A)
val md_theme_light_secondary = Color(0xFF64748B)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFF1F5F9)
val md_theme_light_onSecondaryContainer = Color(0xFF1E293B)
val md_theme_light_tertiary = Color(0xFF4F46E5)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFE0E7FF)
val md_theme_light_onTertiaryContainer = Color(0xFF312E81)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF8FAFC)
val md_theme_light_onBackground = Color(0xFF0F172A)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF0F172A)
val md_theme_light_surfaceVariant = Color(0xFFF1F5F9)
val md_theme_light_onSurfaceVariant = Color(0xFF475569)
val md_theme_light_outline = Color(0xFFCBD5E1)
val md_theme_light_inverseOnSurface = Color(0xFFF1F5F9)
val md_theme_light_inverseSurface = Color(0xFF1E293B)
val md_theme_light_inversePrimary = Color(0xFF94A3B8)
val md_theme_light_surfaceTint = Color(0xFF0F172A)
val md_theme_light_outlineVariant = Color(0xFFE2E8F0)
val md_theme_light_scrim = Color(0xFF000000)

// Status colors
val ColorPendingBg = Color(0xFFFEF3C7)
val ColorPendingText = Color(0xFF92400E)
val ColorApprovedBg = Color(0xFFD1FAE5)
val ColorApprovedText = Color(0xFF065F46)
val ColorRejectedBg = Color(0xFFFEE2E2)
val ColorRejectedText = Color(0xFF991B1B)
