import type { Config } from "tailwindcss";

export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#b7c8e1",
        "surface-tint": "#565e74",
        "on-error": "#ffffff",
        "error": "#ba1a1a",
        "outline": "#76777d",
        "on-primary": "#ffffff",
        "primary-container": "#131b2e",
        "tertiary-container": "#0f0069",
        "on-surface": "#191c1e",
        "outline-variant": "#c6c6cd",
        "on-primary-container": "#7c839b",
        "on-tertiary-container": "#7671ff",
        "surface-container-lowest": "#ffffff",
        "surface": "#f7f9fb",
        "on-tertiary-fixed-variant": "#3323cc",
        "secondary-fixed": "#d3e4fe",
        "surface-container-high": "#e6e8ea",
        "on-secondary-fixed": "#0b1c30",
        "tertiary-fixed-dim": "#c3c0ff",
        "inverse-on-surface": "#eff1f3",
        "on-background": "#191c1e",
        "primary-fixed": "#dae2fd",
        "inverse-surface": "#2d3133",
        "error-container": "#ffdad6",
        "surface-container-highest": "#e0e3e5",
        "on-error-container": "#93000a",
        "surface-bright": "#f7f9fb",
        "tertiary-fixed": "#e2dfff",
        "on-primary-fixed-variant": "#3f465c",
        "secondary-container": "#d0e1fb",
        "surface-container": "#eceef0",
        "surface-container-low": "#f2f4f6",
        "surface-variant": "#e0e3e5",
        "on-tertiary-fixed": "#0f0069",
        "inverse-primary": "#bec6e0",
        "on-secondary-container": "#54647a",
        "on-secondary-fixed-variant": "#38485d",
        "on-secondary": "#ffffff",
        "primary": "#000000",
        "background": "#f7f9fb",
        "tertiary": "#000000",
        "surface-dim": "#d8dadc",
        "primary-fixed-dim": "#bec6e0",
        "on-primary-fixed": "#131b2e",
        "on-surface-variant": "#45464d",
        "secondary": "#505f76",
        "on-tertiary": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "container-max": "1440px",
        "md": "16px",
        "lg": "24px",
        "xl": "32px",
        "sm": "8px",
        "xs": "4px",
        "margin": "24px",
        "unit": "4px",
        "gutter": "20px"
      },
      fontFamily: {
        "headline-lg": ["Inter"],
        "label-sm": ["Inter"],
        "display": ["Inter"],
        "metadata": ["Inter"],
        "body-lg": ["Inter"],
        "headline-md": ["Inter"],
        "body-md": ["Inter"],
        "headline-lg-mobile": ["Inter"]
      },
      fontSize: {
        "headline-lg": ["24px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "label-sm": ["12px", {"lineHeight": "1.4", "letterSpacing": "0.01em", "fontWeight": "500"}],
        "display": ["36px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "metadata": ["11px", {"lineHeight": "1.2", "fontWeight": "500"}],
        "body-lg": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "headline-md": ["18px", {"lineHeight": "1.4", "fontWeight": "600"}],
        "body-md": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "headline-lg-mobile": ["20px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
} satisfies Config;
